version: '3.3'

services:

#  nodejs:
#    image: wingnut/jaegerpocnodejs:1.0
#    networks:
#      - service-discovery-network
#    ports:
#      - 8080:8080
#
#  redisapi:
#    image: wingnut/jaegerpocredisapi:1.0
#    networks:
#      - service-discovery-network
#    ports:
#      - 8081:8081
#
#  postgresapi:
#    image: wingnut/jaegerpocpostgresapi:1.0
#    networks:
#      - service-discovery-network
#    ports:
#      - 8082:8082

  redis:
    image: redis:4.0.2
    networks:
      - service-discovery-network
    ports:
      - 6379:6379

  postgres:
    image: postgres:9.6.5
    networks:
      - service-discovery-network
    ports:
      - 5432:5432

networks:
  service-discovery-network:
