version: '3.3'

services:

  nodejs:
    image: wingnut/jaegerpoc_nodejs:1.0
    networks:
      - service-discovery-network
    ports:
      - 8080:8080
    environment:
      - JAEGER_AGENT_UDP_HOST
      - JAEGER_AGENT_UDP_PORT

  redisapi:
    image: wingnut/jaegerpoc_redisapi:1.0
    networks:
      - service-discovery-network
    ports:
      - 8081:8081
    environment:
      - JAEGER_AGENT_UDP_HOST
      - JAEGER_AGENT_UDP_PORT

  postgresapi:
    image: wingnut/jaegerpoc_postgresapi:1.0
    networks:
      - service-discovery-network
    ports:
      - 8082:8082
    environment:
      - JAEGER_AGENT_UDP_HOST
      - JAEGER_AGENT_UDP_PORT

  redis:
    image: redis:4.0.2
    networks:
      - service-discovery-network
    ports:
      - 6379:6379

  postgres:
    image: postgres:9.6.5
    networks:
      - service-discovery-network
    ports:
      - 5432:5432

networks:
  service-discovery-network:
